name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pytest-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --python ${{ matrix.python-version }}
          pipenv graph
      - name: Test with pytest
        run: |
          pipenv run flake8
          pipenv run pytest
